In [1]:
import numpy as np

Defining array in numpy

In [2]:
digits = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
digits

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
grade = np.array([73,97,45,84])

In [5]:
grade.shape

(4,)

In [6]:
avaerage = grade.mean()

In [7]:
avaerage

74.75

In [8]:
center = 10
change = grade +center

In [9]:
change

array([ 83, 107,  55,  94])

In [10]:
type(grade)

numpy.ndarray

In [11]:
grade.dtype

dtype('int32')

In [12]:
change.dtype

dtype('int32')

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
temp = np.array([10,20,30,45,89,67,90,54,34,12,26,56])

In [15]:
temp.shape

(12,)

In [16]:
temp.reshape(3,2,2)

array([[[10, 20],
        [30, 45]],

       [[89, 67],
        [90, 54]],

       [[34, 12],
        [26, 56]]])

In [17]:
np.arange(10,20,5)

array([10, 15])

In [18]:
np.arange(0,2,2)

array([0])

In [19]:
np.random.rand(2,3)

array([[0.76954445, 0.94090189, 0.79986659],
       [0.58032266, 0.87118596, 0.17665975]])

In [20]:
marks = [[98,97,96,95],[12,34,45,67],[45,67,88,89]]
print(type(marks))
print(marks)
marks_np_array = np.array(marks)
print(type(marks_np_array))
print(marks_np_array)

<class 'list'>
[[98, 97, 96, 95], [12, 34, 45, 67], [45, 67, 88, 89]]
<class 'numpy.ndarray'>
[[98 97 96 95]
 [12 34 45 67]
 [45 67 88 89]]


In [21]:
marks_np_array.shape

(3, 4)

In [22]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.arange(2,10,dtype = float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
access = np.array([[1,2,3],[4,5,6],[7,8,9]])
access

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
access[0,2]

3

In [26]:
access[0:1:2]

array([[1, 2, 3]])

In [27]:
access[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [28]:
access[2,2]

9

In [29]:
#broadcasting in numpy

In [30]:
add1 = np.arange(3)+5
add1

array([5, 6, 7])

In [31]:
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
one +np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [33]:
add2 =np.arange(3).reshape((3,1))

In [34]:
add2

array([[0],
       [1],
       [2]])

In [35]:
add3 = add2 +np.arange(3)
add3

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [36]:
#2x + 6y = 6
#5x +3y = -9

In [37]:
coeff = np.array([[2,6],[5,3]])

In [38]:
const = np.array([6,-9])

In [39]:
solution =  np.linalg.solve(coeff,const)

In [40]:
solution

array([-3.,  2.])

In [41]:
marks = np.array([['Achal',99],['Nikita',99]])
marks

array([['Achal', '99'],
       ['Nikita', '99']], dtype='<U6')

In [42]:
marks1 = np.array(['23','44'])

In [43]:
marks1.dtype
print(marks1)

['23' '44']


In [44]:
add3

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [45]:
#to access the 5 in add3

In [46]:
for x in np.nditer(add3):
    if x==4:
        print(x)

4


In [47]:
add4 =add3.transpose
add4
print(add4)

<built-in method transpose of numpy.ndarray object at 0x000001D795897170>


In [48]:
np.sort(add3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [49]:
data  = np.array([[2,3,4],[7,3,8],[9,6,1]])

In [50]:
data

array([[2, 3, 4],
       [7, 3, 8],
       [9, 6, 1]])

In [51]:
np.sort(data)

array([[2, 3, 4],
       [3, 7, 8],
       [1, 6, 9]])

In [52]:
np.sort(data,axis = 0) #sort rows

array([[2, 3, 1],
       [7, 3, 4],
       [9, 6, 8]])

In [53]:
np.sort(data,axis = 1)#sort colums

array([[2, 3, 4],
       [3, 7, 8],
       [1, 6, 9]])

In [54]:
data.sum()

43

In [55]:
data.max()

9

In [56]:
data.max(axis = 0)

array([9, 6, 8])

In [57]:
data.max(axis = 1)

array([4, 8, 9])

In [58]:
#shape = print shapemof the array
#dtype =
#reshape =

In [59]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
b =list(a)

In [61]:
b

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
a_slice = a[1:5]

In [63]:
a_slice

array([2, 3, 4, 5])

In [64]:
a_slice[1]=1000

In [65]:
a

array([   1,    2, 1000,    4,    5,    6,    7,    8,    9])

In [66]:
#5 types of array creation

In [67]:
#conversion from other python struct
type1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [68]:
type1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
type1.shape

(3, 3)

In [70]:
type1.size

9

In [71]:
np.array({32,45,78})

array({32, 45, 78}, dtype=object)

In [72]:
#type = 
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
lspace = np.linspace(1,70,4)

In [75]:
lspace

array([ 1., 24., 47., 70.])

In [76]:
emp = np.empty((4,6))

In [77]:
emp

array([[1.00068243e-311, 7.50979782e-322, 0.00000000e+000,
        0.00000000e+000, 7.56593016e-307, 1.15998412e-028],
       [2.44171989e+232, 8.00801729e+159, 9.45007090e-076,
        3.21867288e-057, 1.74652355e-076, 6.98352893e-077],
       [2.31901964e-052, 6.01391519e-154, 1.57593361e-052,
        1.03988007e-095, 5.05234784e-038, 8.54289868e-072],
       [1.01059163e+141, 3.77780862e+180, 1.15998412e-028,
        6.48224638e+170, 3.67145870e+228, 1.60895342e+295]])

In [78]:
emp_like = np.empty_like(lspace)

In [79]:
emp_like

array([ 1., 24., 47., 70.])

In [80]:
ide = np.identity(45)

In [81]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [82]:
ide.shape

(45, 45)

In [83]:
arr = np.arange(99)

In [84]:
arr.reshape(33,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [85]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [86]:
x=[[1,2,3],[4,5,6],[8,9,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [87]:
arsum =ar.sum(axis = 0)# appy on all rows on column 

In [88]:
arsum

array([13, 16,  9])

In [89]:
arsum =ar.sum(axis = 1)
arsum

array([ 6, 15, 17])

In [90]:
print(ar)
print("*****************")
print(ar.T)

[[1 2 3]
 [4 5 6]
 [8 9 0]]
*****************
[[1 4 8]
 [2 5 9]
 [3 6 0]]


In [91]:
ar.flat

In [92]:
for i in ar.flat:#iterator
    print(i)

1
2
3
4
5
6
8
9
0


In [93]:
ar.ndim

2

In [94]:
ar.size

9

In [95]:
ar.nbytes

36

In [96]:
oned = np.array([1,3,2,4])

In [97]:
oned.argmax()#return the index value of the max element

3

In [98]:
oned.argmin()#return the index value of the min element

0

In [99]:
oned.argsort()#index of sorted arraya

array([0, 2, 1, 3], dtype=int64)

In [100]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [101]:
ar.argmin()

8

In [102]:
ar.argmax()

7

In [103]:
ar.argmax(axis = 0)#return index value of colums

array([2, 2, 1], dtype=int64)

In [104]:
ar.argmax(axis = 1)#return index value of rows

array([2, 2, 1], dtype=int64)

In [105]:
ar.argsort()#return the index value of sorted data 

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [106]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.82842712, 3.        , 0.        ]])

In [107]:
ar.sum()

38

In [108]:
ar.min()

0

In [109]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [110]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [111]:
np.count_nonzero(ar)

8

In [112]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [113]:
import sys

In [114]:
ch = [0,4,55,2]

In [115]:
npar =np.array(ch)

In [116]:
sys.getsizeof(1)*len(ch)

112

In [117]:
npar.itemsize*npar.size

16

In [118]:
ch[0:4]

[0, 4, 55, 2]

In [119]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [120]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b) 

0

In [121]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [122]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])